### ISSUE TITLE
Rename this GitHub organization

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoportal#427]
This name of our project has been changed to "Big Ten Academic Alliance Geospatial Information Network".

We will need to rename a number of our online services, including this GitHub organization. Perhaps we can choose something shorter, like `geobtaa`? 

This does not need to happen immediately, and we can make sure to review https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization first. 

@mberkowski @ewlarson Please add a comment to this issue for things we need to be aware of before renaming and when you think would be a good time to do it.

**Comment by mberkowski** [comment]
The main impact would be on things like the About page in the google site, which we have control over. It could potentially break similar links to the org if they exist on sites we do not have control over. Repo and code-wise, I would expect everything to just continue working like it does now because repos automatically redirect. It can be a minor hassle to update .git/config to point remotes to the true new org location.

What about CircleCI? I don't think it would be impacted, but can't say for certain. @ewlarson may no better.

**Comment by karenmajewicz** [comment]
We will change it to geobtaa this week.

**Comment by karenmajewicz** [comment]
@mberkowski I am ready to make this change. Will this affect your workflow as Eric commits new code this week? (Ansible?)

**Comment by mberkowski** [comment]
@karenmajewicz I don't expect any issues. GH should redirect automatically and if there are problems, they would come later on deployments and be trivial to solve.

**Comment by karenmajewicz** [comment]
Now changed: https://github.com/geobtaa

Investigating possible fallout across documentation sites.
